[package]
name = "discord_chess"
version = "0.1.0"
authors = ["TheOnlyMrCat <signupforforums5@gmail.com>"]
edition = "2018"
license = "MIT"

[profile.dev]
opt-level = 1

[dependencies]
serenity = "0.8"
lazy_static = "1.4"
chess = "3.1"
rand = "0.7"
regex = "1.3"
raster = "0.2"
png = "0.16"